default:
  adapter: 'postgresql'
  host: 'localhost'
  username: 'postgres'
  password: 'password'
  database: 'test'

heroku:
  adapter: 'postgresql'
  encoding: unicode
  pool: 20
  url: <%= ENV['DATABASE_URL'] %>
