default:
  adapter: 'postgresql'
  host: 'localhost'
  username: 'postgres'
  password: 'password'
  database: 'test'

heroku:
  adapter: 'postgresql'
  host: <%= ENV['DATABASE_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>